const DIFICULTY = 4
const MINE_RATE = 3000 // 3 seconds in miliseconds
const INITIAl_BALANCE = 1000
const MINING_REWARD = 10
const MIN_NUM_TRANSACTIONS_TO_MINE = 5

module.exports = { DIFICULTY, MINE_RATE, INITIAl_BALANCE, MINING_REWARD, MIN_NUM_TRANSACTIONS_TO_MINE }